#!/bin/bash

echo "🏗️  Building Standalone App in Xcode"
echo ""
echo "EAS cloud builds are failing due to dependency issues."
echo "Building locally in Xcode is the most reliable method."
echo ""

# Open Xcode
open ios/VIBEDEBUG.xcworkspace

echo "✅ Xcode opened!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Follow these steps to create a STANDALONE app:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Product → Scheme → Edit Scheme..."
echo "2. Click 'Run' in left sidebar"
echo "3. Change 'Build Configuration' from 'Debug' to 'Release'"
echo "4. Click 'Close'"
echo ""
echo "5. Product → Archive"
echo "   (This will build and create a standalone .ipa)"
echo ""
echo "6. When Organizer opens:"
echo "   - Select your archive"
echo "   - Click 'Distribute App'"
echo "   - Choose 'Ad Hoc'"
echo "   - Click 'Next' through the steps"
echo "   - Click 'Export'"
echo ""
echo "7. Save the .ipa file"
echo ""
echo "8. Install on iPhone:"
echo "   - Connect iPhone via USB"
echo "   - Drag .ipa to iPhone in Finder"
echo "   - Or use Apple Configurator"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ This creates a TRUE STANDALONE app that:"
echo "   - Works anywhere (no Mac needed)"
echo "   - Has all JavaScript bundled"
echo "   - Includes all animations"
echo "   - Is a complete production-ready app"
echo ""
echo "🎉 Follow the steps above to build!"
