#!/usr/bin/env python3
import csv

# Read and append activities
activities_data = """bucharest-traditional-food-tour,Bucharest Traditional Food Tour,culinary,"food_tour,street_food","Taste sarmale, mici, covrigi, and sweet cozonac while exploring Old Town and historic markets with a local foodie guide. Learn dish origins, ordering etiquette, and how to pair Romanian beers and wines. Vegetarian alternatives usually available; small groups keep it personal.",Bucharest,București,44.4319,26.1025,150,210,all,either,medium,beginner,"social,creative,explorer","urban,market",none,"small-group,group,solo","booking-required",low,ok_in_rain,"daytime,evening",in-city,none_required,$$,,https://www.getyourguide.com/bucharest-l111/food-drinks-tc103/,"Multiple operators on GetYourGuide/Viator"
bucharest-romanian-cooking-class,Romanian Cooking Class in Bucharest,culinary,"cooking_class,home_experience","Chop, simmer, and season your own three-course Romanian meal—think ciorbă, sarmale, and papanasi—guided by a local chef. Hands-on instruction covers spice blends, plating, and stories behind classic dishes. Sit down to enjoy your creations with a glass of local wine.",Bucharest,București,44.4408,26.1004,180,210,all,indoor,medium,beginner,"creative,cozy,romantic","urban",provided,"date,small-group,solo","booking-required",low,all_weather,"evening,daytime",in-city,"technique,none_required",$$,,https://www.viator.com/Bucharest/d499-ttd/cooking-classes/d22290,"Multiple studios; check dates"
cluj-street-food-tour,Cluj-Napoca Street Food & Market Tasting,culinary,"food_tour,market","Sample Transylvanian cheeses, cured meats, chimney cake, and specialty coffee on a guided walk through Cluj's central squares and marketplace. Meet vendors, learn regional flavors, and pick up tips on ordering local favorites.",Cluj-Napoca,Cluj,46.7707,23.5899,120,180,all,outdoor,medium,beginner,"explorer,creative,social","urban,market",none,"small-group,solo","booking-required",low,wind_sensitive,"daytime",in-city,none_required,$$,,https://www.getyourguide.com/cluj-napoca-l32107/food-drinks-tc103/,"Runs most days in season"
sibiu-food-tour,Sibiu Old Town Food Tour,culinary,"food_tour,market","Discover Saxon-influenced recipes on a curated tasting route: soups and stews, artisan bread, cured meats, and local desserts. Your guide shares culinary history and modern slow-food projects around Sibiu.",Sibiu,Sibiu,45.7926,24.1513,120,180,all,either,chill,beginner,"cozy,creative,explorer","urban,market",none,"small-group,friends","booking-required",low,ok_in_rain,daytime,in-city,none_required,$$,,https://sibiufoodtours.com/,"Independent operator; check calendar"
timisoara-craft-beer-tasting,Timișoara Craft Beer Tasting Crawl,culinary,"beer_tasting,bar_hopping","Explore Romania's craft scene with flights at two taprooms. Learn styles from NEIPA to barrel-aged stouts, how to read labels, and what pairs with local snacks. Perfect prelude to a night out.",Timișoara,Timiș,45.7552,21.2276,120,150,all,indoor,medium,beginner,"social,creative","urban",none,"friends,group,solo","booking-recommended",low,all_weather,evening,in-city,none_required,$$,,https://www.beretatm.ro/; https://clinicadebere.ro/,"Taprooms rotate seasonal lists"
iasi-winery-visit-gramma,Gramma Winery Visit & Tasting (Iași),culinary,"wine_tasting,cellar_tour","Drive into the Bârnova hills for a guided tasting of aromatic whites and blends. Stroll the vines, see the cellar, and learn about Moldavian terroir. Pair with local cheeses or snacks on request.",Iași,Iași,47.0686,27.6421,90,120,shoulder,either,chill,beginner,"romantic,relaxed,creative","valley,hill",provided,"date,small-group","booking-required",low,ok_in_rain,daytime,day-trip,none_required,$$,,https://grammawines.ro/,"Advance reservation required"
domeniul-bogdan-winery-tour,Domeniul Bogdan Organic Winery Tour,culinary,"wine_tasting,organic","Visit an organic estate in Dobrogea near Constanța. Walk the vineyard, learn biodynamic practices, and taste award-winning wines in a modern cellar. Ideal summer day-trip from the coast.",Peștera,Constanța,44.2720,28.1828,120,150,summer,either,chill,beginner,"creative,relaxed","valley,hill,resort",provided,"date,small-group","booking-required",low,heat_sensitive,daytime,day-trip,none_required,$$,,https://domeniulbogdan.ro/,"English tours available"
dealu-mare-winery-trio,Dealu Mare Winery Trio (Lacerta/Serve/Budureasca),culinary,"wine_tasting,day_trip","Spend a full day tasting across three flagship estates in Dealu Mare. Compare styles with a sommelier host, tour barrel rooms, and enjoy viewpoints over rolling hills. Transfers and lunch add-ons available.",Ceptura,Prahova,45.0466,26.3533,360,480,shoulder,either,medium,beginner,"romantic,creative,relaxed","valley,hill",provided,"date,small-group","booking-required",low,ok_in_rain,daytime,day-trip,none_required,$$$,,https://serve.ro/en/; https://www.lacertawinery.ro/en; https://budureasca.ro/en/,"Plan ~3 wineries"
constanta-seafood-tasting,Constanța Seafood Tasting Experience,culinary,"seafood_tasting,local_dining","Feast on Black Sea catch—fried hamsii, rapana, mussels—and Dobrogean specialties with seaside views. Learn what's in season, typical cooking methods, and recommended local wines.",Constanța,Constanța,44.1768,28.6615,90,120,summer,either,chill,beginner,"cozy,romantic,creative","coast,urban",none,"date,small-group,friends",booking-recommended,low,heat_sensitive,"daytime,evening",in-city,none_required,$$,,https://www.pescarialuimatei.ro/; https://restaurantreyna.ro/,"Popular seaside restaurants"
bucharest-improv-workshop,Improvisation Theatre Workshop (Bucharest),creative,"improv,acting,workshop","Loosen up with games that build listening, spontaneity, and storytelling. A professional improv coach guides warmups and short-form scenes—no experience needed. Great confidence builder and social icebreaker.",Bucharest,București,44.4329,26.1063,120,150,all,indoor,medium,beginner,"creative,social,explorer","urban",none,"solo,group,friends","booking-required",low,all_weather,evening,in-city,none_required,$$,,https://improvisneyland.ro/,"Workshops in English listed periodically"
bucharest-salsa-bachata-beginner,Salsa/Bachata Beginner Class (Bucharest),creative,"dance,latin","Learn basic steps and partner connection in a friendly studio. Rotate partners, practice timing, and finish with a short social dance. Sneakers OK; no partner required.",Bucharest,București,44.4477,26.0931,60,90,all,indoor,medium,beginner,"creative,social","urban",none,"solo,group,friends","booking-required",low,all_weather,evening,in-city,"balance,none_required",$$,,https://salsafactory.ro/,"Weekly socials available"
bucharest-cyanotype-workshop,Cyanotype & Alternative Photography Workshop,creative,"photography,printing,workshop","Create sun-printed blue images using vintage cyanotype chemistry. Compose botanicals or photo negatives, coat paper, expose, and wash to reveal unique prints. All materials provided.",Bucharest,București,44.4389,26.1075,120,150,all,indoor,chill,beginner,"creative,mindful","urban",provided,"solo,small-group","booking-required",low,all_weather,daytime,in-city,none_required,$$,,https://allkimik.ro/,"English-friendly classes"
bucharest-screenprinting-workshop,Screen Printing Basics (Bucharest),creative,"printmaking,workshop","Design, burn a screen, and pull your first T-shirt or poster print under an artist's guidance. Learn inks, mesh counts, and registration tips, then take home your custom piece.",Bucharest,București,44.4389,26.1075,150,180,all,indoor,medium,beginner,"creative,explorer","urban",provided,"small-group,friends","booking-required",low,all_weather,daytime,in-city,none_required,$$,,https://allkimik.ro/,"Materials included"
sibiu-icon-painting-workshop,Icon on Glass Workshop (ASTRA Museum),creative,"folk_art,painting","Discover a Transylvanian folk technique painting icons on glass. Trace motifs, apply colors in reverse, and seal your piece to take home. Hosted by craftspeople inside the open-air museum.",Sibiu,Sibiu,45.7575,24.1139,120,150,shoulder,indoor,chill,beginner,"creative,cozy","park,urban",provided,"family,small-group","booking-required",low,ok_in_rain,daytime,in-city,none_required,$$,,https://muzeulastra.ro/,"Workshops by request"
sibiu-weaving-loom-workshop,Weaving on the Loom (ASTRA Museum),creative,"weaving,craft","Try hand-weaving on a traditional loom, learning basic patterns and warp/weft setup. Friendly facilitators guide you through a small sample you can keep.",Sibiu,Sibiu,45.7575,24.1139,90,120,shoulder,indoor,chill,beginner,"creative,mindful","park,urban",provided,"family,small-group,solo","booking-required",low,ok_in_rain,daytime,in-city,none_required,$$,,https://muzeulastra.ro/,"Reserve ahead"
bucharest-romanian-crashcourse,Romanian Language Crash Course (Bucharest),learning,"language,workshop","Pick up essentials—greetings, numbers, food words, and travel phrases—in a fast-paced intro led by a certified teacher. Materials provided; small groups keep it interactive.",Bucharest,București,44.4442,26.0962,90,120,all,indoor,medium,beginner,"creative,explorer","urban",provided,"solo,small-group","booking-required",low,all_weather,"morning,evening",in-city,none_required,$$,,https://rolang.ro/en/,"Rolang School central campus"
bucharest-coffee-brewing-class,Specialty Coffee Brewing Class (Bucharest),learning,"coffee,class","Dial in your pour-over and AeroPress with a barista trainer: grind size, ratios, and extraction. Practice on pro gear and taste differences across recipes and origins.",Bucharest,București,44.4367,26.0976,90,120,all,indoor,medium,beginner,"creative,explorer","urban",provided,"solo,small-group","booking-required",low,all_weather,"morning,afternoon",in-city,none_required,$$,,https://origocoffee.ro/,"ORIGO training studio"
cluj-barista-basics,Barista Basics Workshop (Cluj),learning,"coffee,class","Hands-on session covering espresso dialing, milk steaming, and latte art basics at a specialty roastery's training lab. Ideal for home enthusiasts and aspiring baristas.",Cluj-Napoca,Cluj,46.7715,23.5929,120,150,all,indoor,medium,beginner,"creative,explorer","urban",provided,"solo,small-group","booking-required",low,all_weather,"morning,afternoon",in-city,none_required,$$,,https://academy.meron.coffee/,"Meron Academy schedule"
sibiu-cooking-class,Sibiu Traditional Cooking Class,learning,"cooking_class,market","Shop for seasonal ingredients then cook a traditional menu with a local chef. Learn techniques, plating, and regional stories before sharing the meal together.",Sibiu,Sibiu,45.7926,24.1513,180,240,all,indoor,medium,beginner,"creative,cozy,romantic","urban,market",provided,"date,small-group","booking-required",low,all_weather,"morning,afternoon",in-city,"technique,none_required",$$$,,https://sibiufoodtours.com/,"Private classes on request"
bucharest-wine-introduction-class,Intro to Romanian Wine (Bucharest),learning,"wine_tasting,class","Taste through key Romanian grapes—Fetească Albă, Fetească Neagră, Tămâioasă—while learning wine structure, aroma wheels, and food pairing basics with a sommelier.",Bucharest,București,44.4435,26.0978,90,120,all,indoor,chill,beginner,"creative,relaxed","urban",provided,"date,small-group","booking-required",low,all_weather,evening,in-city,none_required,$$,,https://wineful.ro/,"Wine bar masterclasses; check dates"
bucharest-mindfulness-soundbath,Sound Bath & Breathwork (Bucharest),mindfulness,"sound_healing,breathwork","Slow down with a facilitator-led session using crystal bowls and gentle breath techniques to release stress and improve sleep. Mats and blankets provided; no experience needed.",Bucharest,București,44.4428,26.1001,60,90,all,indoor,chill,beginner,"mindful,relaxed","urban",provided,"solo,small-group","booking-required",low,all_weather,evening,in-city,none_required,$$,,https://yoginovate.ro/,"Workshops scheduled monthly"
turda-saltmine-halotherapy,Halotherapy & Mindful Walk – Turda Salt Mine,mindfulness,"salt_therapy,wellness","Descend into the otherworldly chambers of Salina Turda for clean, mineral-rich air. Stroll the galleries, sit in quiet corners for mindful breathing, and enjoy the subterranean lake views.",Turda,Cluj,46.5874,23.7876,90,150,all,either,chill,beginner,"mindful,relaxed,explorer","cave,urban",none,"solo,family,small-group","booking-optional",low,cold_friendly,daytime,day-trip,none_required,$$,,https://salinaturda.eu/,"Tickets at entrance"
praid-saltmine-wellness,Salt Mine Wellness Session – Praid,mindfulness,"salt_therapy,wellness","Ride underground buses to vast chambers fitted with relaxation areas and playgrounds. Breathe deeply during a guided stretch or quiet meditation to benefit from the saline microclimate.",Praid,Harghita,46.5528,25.1265,120,180,all,either,chill,beginner,"mindful,relaxed","cave,valley",none,"family,solo","booking-optional",low,cold_friendly,daytime,day-trip,none_required,$,,https://salinapraid.ro/,"Seasonal hours vary"
therme-sauna-rituals,Therme Sauna Rituals & Mindful Heat,mindfulness,"sauna,aufguss","Join a curated series of sauna rituals (aufguss) with scented steam, guided breathing, and cool-down cycles to deepen relaxation. Rotate hot/cold exposure for a meditative reset.",Balotești,Ilfov,44.6054,26.0806,90,150,all,indoor,chill,beginner,"mindful,relaxed","resort,urban",provided,"solo,date,small-group","booking-optional",low,all_weather,evening,nearby,none_required,$$,,https://therme.ro/en/,"Check ritual schedule"
eforie-ana-aslan-spa-day,Ana Aslan Health Spa Day – Eforie Nord,wellness,"spa,balneary","Rejuvenate with seawater pools, mud packs, and tailored therapies at a historic Black Sea balneary center. Combine beach time with a focused wellness session or package.",Eforie Nord,Constanța,44.0697,28.6336,120,240,summer,indoor,chill,beginner,"relaxed,cozy","coast,resort",provided,"solo,date","booking-required",low,heat_sensitive,"daytime,evening",day-trip,none_required,$$$,,https://www.anahotels.ro/en/hotels/europa-eforie-nord,"Medical consults available"
eforie-aqvatonic-spa-pass,Aqvatonic Med Spa Pass – Eforie Nord,wellness,"spa,thermal_pool","Follow a hydrotherapy circuit through underwater jets, cascades, and saunas at a dedicated med-spa by the sea. Family-friendly slots and adult-only times available.",Eforie Nord,Constanța,44.0621,28.6305,120,180,summer,indoor,medium,beginner,"relaxed,cozy","coast,resort",provided,"family,solo,date","booking-optional",low,heat_sensitive,"daytime,evening",day-trip,none_required,$$,,https://aqvatonic.ro/,"Steaua de Mare complex"
potcoava-horseback-trail-leaota,Leaota Mountain Horseback Trail Ride,nature,"horseback,trail_ride","Ride calm, well-trained horses across forest tracks and alpine meadows with panoramic Leaota views. Guides match routes to ability; helmets provided. Great nature fix within reach of Bucharest.",Runcu,Dâmbovița,45.2452,25.3027,90,180,shoulder,outdoor,medium,beginner,"explorer,romantic,relaxed","forest,mountain,valley",helmet,"small-group,date","guide-required,booking-required",moderate,wind_sensitive,"daytime,sunset",day-trip,"balance,none_required",$$$,,https://potcoava.ro/,"Potcoava Mountain Hideout ranch"
bucegi-babele-sphinx-hike,Bucegi Plateau Hike: Babele & Sphinx,nature,"hiking,scenic","Ride the cable car then cross the wind-shaped plateau to the Babele huts and iconic Sphinx rock. A guide sets an easy pace, explains geology and legends, and manages weather calls.",Bușteni,Prahova,45.4141,25.5166,180,300,shoulder,outdoor,medium,beginner,"explorer,adventurous","mountain,forest",none,"small-group,group","guide-recommended,booking-required",moderate,wind_sensitive,"daytime",day-trip,"endurance,none_required",$$,,https://www.getyourguide.com/bucharest-l111/bucegi-tours-tc1117/,"Weather-dependent cable car"
apuseni-ice-cave-tour,Scărișoara Ice Cave & Apuseni Views,nature,"cave,hiking","Head into Apuseni to visit one of the world's largest underground glaciers, then walk to viewpoints over karst valleys. Entrances are managed; guides handle timing and access.",Gârda de Sus,Alba,46.4934,22.8118,300,480,shoulder,outdoor,medium,beginner,"explorer,creative","mountain,cave,valley",none,"small-group","guide-required,booking-required",moderate,cold_friendly,daytime,day-trip,"navigation,none_required",$$$,,https://apuseni-experience.ro/,"Road conditions vary"
cheile-turzii-hike,Cheile Turzii Gorge Guided Hike,nature,"hiking,geology","Follow a spectacular limestone gorge with suspension bridges and wildflower meadows. Your guide shares geology and local stories, with optional photo stops on scenic ledges.",Tureni,Cluj,46.5546,23.7220,150,210,shoulder,outdoor,medium,beginner,"explorer,adventurous","valley,forest,mountain",none,"small-group,solo","guide-recommended,booking-required",moderate,wind_sensitive,daytime,day-trip,"endurance,none_required",$$,,https://www.getyourguide.com/cluj-napoca-l32107/day-trips-tc172/,"Spring–autumn best"
retezat-day-hike,Retezat National Park Day Hike,nature,"hiking,alpine_lakes","Tackle a classic trail past glacial lakes under jagged peaks in one of Romania's wildest parks. A licensed mountain guide sets pace and route, adjusting to group ability.",Râușor,Hunedoara,45.3965,22.8576,360,540,shoulder,outdoor,high,intermediate,"adventurous,explorer","mountain,lake",none,"small-group","guide-required,booking-required",exposed,wind_sensitive,daytime,overnight,"endurance,navigation",$$$,,https://romania-active.com/; https://muntiinostri.ro/,"Hardy footwear essential"
viscri-bike-pastures,Viscri Pastures Bike & Haystack Walk,nature,"cycling,walking","Pedal quiet lanes around UNESCO-listed Viscri, stopping for haystack views and village life. Option to switch to an easy pastoral walk if you prefer on-foot exploration.",Viscri,Brașov,46.0532,25.0909,120,210,summer,outdoor,medium,beginner,"relaxed,explorer","hill,valley,urban",provided,"small-group,family","booking-recommended",low,heat_sensitive,"daytime,sunset",day-trip,"balance,none_required",$$,,https://www.viscri125.ro/,"Bike rentals available"
"""

with open('data/activities.csv', 'a', encoding='utf-8') as f:
    for line in activities_data.strip().split('\n'):
        f.write(line + '\n')

print(f"✅ Appended {len(activities_data.strip().split(chr(10)))} activities")

# Now write venues using CSV library for proper handling
import io

venues_csv_text = """activity_slug,name,address,city,region,latitude,longitude,booking_url,website,phone,price_tier,seasonality,blurb,tags_equipment,tags_requirement,tags_context,tags_cost_band,opening_hours_monday,opening_hours_tuesday,opening_hours_wednesday,opening_hours_thursday,opening_hours_friday,opening_hours_saturday,opening_hours_sunday,source_url,notes
bucharest-traditional-food-tour,Old Town Meeting Point (Lipscani),Str. Lipscani 1,Bucharest,București,44.4319,26.1025,https://www.getyourguide.com/bucharest-l111/food-drinks-tc103/,https://www.getyourguide.com/bucharest-l111/food-drinks-tc103/,,$$,all,"Central meet for small-group food walks through markets and eateries.",none,booking-required,"small-group,solo",$$,10:00-20:00,10:00-20:00,10:00-20:00,10:00-20:00,10:00-21:00,10:00-21:00,10:00-20:00,https://www.getyourguide.com/bucharest-l111/food-drinks-tc103/,"Operator varies by date"
"""

# Parse the first venue to continue the pattern - it's getting too long, let me use a file instead
print("Creating venues file...")
