#!/usr/bin/env python3
import csv

# New activities data
activities = [
    ["karaoke-night-mojo-bucharest", "Karaoke Night at Mojo Music Club", "social", "karaoke,live_music", "Grab a mic in Bucharest's Old Town and sing your heart out at Mojo—Romania's original seven-nights-a-week karaoke institution. Multiple bars, a big song catalog, and friendly hosts keep the energy high through late hours. Perfect for groups, meetups, and new friends in the city.", "Bucharest", "București", "44.4318", "26.1009", "120", "300", "all", "indoor", "high", "beginner", "social,adrenaline", "urban", "none", "friends,group,solo", "booking-optional,none", "low", "all_weather", "evening,night", "in-city", "none_required", "$$", "", "https://mojomusic.ro/", "Phone on site; Old Town location"],
    ["bowling-billiards-trickshot", "Fun Bowling & Billiards at Trickshot", "social", "bowling,billiards,arcade", "Mix games, great music, and a lively crowd at Trickshot's glossy bowling lounges. Reserve lanes for teams, grab craft cocktails and snacks, and challenge friends at billiards and arcade cabinets. A quintessential social night out with easy online/phone booking.", "Bucharest", "București", "44.4787", "26.1018", "60", "180", "all", "indoor", "medium", "beginner", "social,relaxed", "urban", "none", "friends,group,team", "booking-required", "low", "all_weather", "evening,night", "in-city", "none_required", "$$", "", "https://trickshot.ro/en/trickshot-promenada/", "Promenada & Mega Mall locations; phone on site"],
    ["vr-arena-gateway-bucharest", "Free-Roam VR Arena & Escape Games (Gateway VR)", "social", "vr_arena,vr_escape_room,gaming", "Step into a free-roam VR arena and cooperative escape games at Gateway VR Studio. Battle zombies, crack Ubisoft-style VR puzzles, or race simulators. Staff guide first-timers, making it perfect for groups, team socials, and birthdays.", "Bucharest", "București", "44.4805", "26.0555", "60", "120", "all", "indoor", "medium", "mixed", "social,adrenaline,creative", "urban", "provided", "friends,group,small-group", "booking-required,guide-optional", "low", "all_weather", "evening,daytime", "in-city", "none_required", "$$", "", "https://vrstudio.ro/en/", "Address/phone on site"],
    ["escape-room-quest-bucharest", "Immersive Escape Room Adventure", "social", "escape_room,puzzle", "Race the clock as a team inside cinematic sets. Choose themes from Indiana Jones to horror at top venues; expect tactile puzzles, hidden mechanisms, and great set design. Ideal for friends or coworkers looking for a shared triumph.", "Bucharest", "București", "44.4401", "26.1011", "60", "90", "all", "indoor", "medium", "mixed", "social,explorer", "urban", "none", "friends,group,team", "booking-required", "low", "all_weather", "evening,daytime", "in-city", "technique", "$$", "", "https://escapearena.ro/en/", "Use either Escape Arena or The Void"],
    ["candlelight-concerts-bucharest", "Romantic Candlelight Concert (Fever)", "romance", "live_music,classical", "Hundreds of candles, intimate venues, and string quartets covering classical and modern hits. Candlelight events pop up around Bucharest's most atmospheric halls—perfect for a date night with effortless booking and assigned seating.", "Bucharest", "București", "44.4350", "26.1025", "60", "90", "all", "indoor", "chill", "beginner", "romantic,cozy", "urban", "none", "date,small-group", "booking-required", "low", "all_weather", "evening,night", "in-city", "none_required", "$$", "", "https://feverup.com/en/bucharest/candlelight", "Rotating venues; check listing"],
    ["stargazing-urseanu-observatory", "Stargazing at Vasile Urseanu Observatory", "romance", "stargazing,astronomy_tour", "Peer through telescopes on guided public nights at Bucharest's historic observatory. Staff point out planets, double stars, and seasonal constellations, with occasional rooftop views and exhibits. A quiet, inspiring date option in the city.", "Bucharest", "București", "44.4465", "26.0969", "60", "120", "shoulder", "either", "chill", "beginner", "romantic,mindful,explorer", "urban", "none", "date,small-group,solo", "booking-optional,none", "low", "wind_sensitive", "evening,night", "in-city", "none_required", "$", "", "https://observator.astronomiei.ro/", "Check program nights"],
    ["herastrau-lake-boat-ride", "Boat Ride on Herăstrău Lake", "romance", "boat_rental,hydrobike", "Glide across Herăstrău Lake by rowboat, pedalo, or join a mini-cruise. Central docks operate spring–autumn with simple on-site tickets—sunset sessions are especially scenic. A relaxed, wallet-friendly date or friends' hangout.", "Bucharest", "București", "44.4721", "26.0822", "30", "60", "summer", "outdoor", "chill", "beginner", "romantic,relaxed", "lake,urban", "provided", "date,friends,small-group", "booking-optional,none", "low", "wind_sensitive", "daytime,sunset", "in-city", "none_required", "$", "", "https://alpab.ro/servicii-agrement/", "ALPAB official tariffs"],
    ["karting-bucharest", "Go-Karting: VMAX (Indoor) or AMCKart (Outdoor)", "adventure", "karting,indoor_outdoor", "Chase lap times on Bucharest's most popular tracks. Indoors, VMAX Romexpo runs torquey electric karts on a multi-level track; outdoors, AMCKart Tunari offers long straights and night sessions. Arrive & drive or book events for groups.", "Bucharest", "București", "44.4733", "26.0769", "10", "60", "all", "either", "high", "mixed", "adrenaline,adventurous,social", "urban", "provided", "friends,group,team", "booking-optional,lesson-recommended", "moderate", "all_weather", "daytime,evening", "in-city", "balance", "$$", "", "https://vmaxromexpo.ro/", "Helmet/cagoule provided or rentable"],
    ["indoor-climbing-bucharest", "Indoor Climbing Session (Top-rope & Bouldering)", "adventure", "climbing_gym,belay_class", "Learn knots, belay, and movement on varied walls with rental gear available. Suitable for first-timers or training sessions, with intro classes and auto-belays at leading gyms. Great cross-training and a social way to get active.", "Bucharest", "București", "44.4500", "26.1480", "60", "120", "all", "indoor", "medium", "mixed", "adventurous,explorer", "urban", "rental-gear", "friends,solo,group", "booking-optional,lesson-recommended", "low", "all_weather", "daytime,evening", "in-city", "balance", "$$", "", "https://verticalspirit.ro/", "Use Vertical Spirit / Climb Again"],
    ["laser-tag-bucharest", "Laser Tag Battles", "sports", "laser_tag,arena", "Fast-paced team matches with vests, scoreboards, and neon mazes. Ideal for office outings or birthdays; most venues offer private games, party rooms, and simple per-session pricing.", "Bucharest", "București", "44.3985", "26.1305", "30", "90", "all", "indoor", "high", "beginner", "adrenaline,social", "urban", "provided", "friends,group,team", "booking-required", "low", "all_weather", "evening,daytime", "in-city", "technique", "$$", "", "https://lasermaxx.ro/", "Multiple arenas citywide"],
    ["padel-romexpo", "Padel Court Booking (Romexpo Area)", "sports", "padel,court_booking", "Book doubles at modern indoor/outdoor padel courts near Romexpo. Rackets and balls are rentable; many clubs run beginner socials, ladders, and coaching. Easy to reach from the north side business district.", "Bucharest", "București", "44.4765", "26.0710", "60", "90", "all", "either", "medium", "mixed", "social,adventurous", "urban", "rental-gear", "friends,group,small-group", "booking-required", "low", "all_weather", "evening,daytime", "in-city", "balance", "$$", "", "https://playtomic.io/padelx-romexpo-bucharest/venues", "Use Playtomic to book courts"],
    ["five-a-side-football-bucharest", "5-a-Side Football Pitch Hire (South)", "sports", "football,5aside", "Round up friends and rent a FIFA-sized 5-a-side pitch with lights and quality turf in the city's south. Book recurring slots, add changing rooms, and optionally hire a referee for mini-leagues.", "Bucharest", "București", "44.3941", "26.1315", "60", "120", "all", "outdoor", "high", "mixed", "social,adrenaline", "urban", "none", "friends,team,group", "booking-required", "low", "all_weather", "evening,night", "in-city", "endurance", "$$", "", "https://argman.ro/", "Near Vitan-Bârzești; multiple pitches"]
]

# Append to activities.csv
with open('data/activities.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    for row in activities:
        writer.writerow(row)

print(f"✅ Appended {len(activities)} new activities to activities.csv")
