UPDATE activities SET energy_level = 'medium' WHERE name = '321sport Community Run';
UPDATE activities SET energy_level = 'high' WHERE name = '5-a-Side Football Pitch Hire (South)';
UPDATE activities SET energy_level = 'medium' WHERE name = '50m Lap Swim (Olympic Pool)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Abel''s Wine Bar Discovery Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Adult Ceramics Starter (Școala Populară de Arte Cluj)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Adventure Park Brașov Mega Zip & Ropes';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Affordable Lengths at Olimpia (Iancului)';
UPDATE activities SET energy_level = 'low' WHERE name = 'After-Work Dip at Daimon Wellness (Tineretului)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Alt & Electronic Nights at Control Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Alt-Rock & Indie Nights at Expirat';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Amateur Cooking at Atelierele ILBAH';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Amateur Cooking at Atelierele ILBAH';
UPDATE activities SET energy_level = 'low' WHERE name = 'Ana Aslan Health Spa Day – Eforie Nord';
UPDATE activities SET energy_level = 'low' WHERE name = 'Ana Spa Daypass at Crowne Plaza';
UPDATE activities SET energy_level = 'low' WHERE name = 'Aquapark Nymphaea Day Pass';
UPDATE activities SET energy_level = 'low' WHERE name = 'Aqvatonic Med Spa Pass – Eforie Nord';
UPDATE activities SET energy_level = 'low' WHERE name = 'Aromatherapy & natural perfume workshop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Arthouse Cinema Session (Elvire Popesco)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Artisan Techniques at Artisan Cooking Classes';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Artisan Techniques at Artisan Cooking Classes';
UPDATE activities SET energy_level = 'low' WHERE name = 'ASTRA Museum Hands-on Crafts Workshop';
UPDATE activities SET energy_level = 'medium' WHERE name = 'ATV/Quad Biking (Cernica Forest)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'ATV/Quad Off-Road Tour – Zărnești & Plaiul Foii';
UPDATE activities SET energy_level = 'high' WHERE name = 'Avalanche Skills & Freetouring – Bâlea';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Azuga Guided Snowmobile Ride';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Backcountry Snowmobile Tour – Harghita-Mădăraș';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Badminton Courts & Group Play (Sun Plaza)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Bâlea Ice Climbing Intro';
UPDATE activities SET energy_level = 'high' WHERE name = 'Bâlea Ski Mountaineering Clinic (Făgăraș)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Balvanyos Forest Spa Ritual';
UPDATE activities SET energy_level = 'low' WHERE name = 'Barista Basics Workshop (Cluj)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Basketball Court Booking (Full Court Run)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Beach Club Night at EGO Mamaia';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Beach Tennis Doubles';
UPDATE activities SET energy_level = 'low' WHERE name = 'Bear Watching from a Hide (Brașov)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Beer O''Clock: Craft & Imports';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Beginner Archery Class (Sector 5 Range)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Beluga: Music & Cocktails (Old Town)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Berăria H Beer Hall & Live Shows';
UPDATE activities SET energy_level = 'low' WHERE name = 'BERĂRIA H Live & Beer Hall';
UPDATE activities SET energy_level = 'high' WHERE name = 'Bicaz Gorges Ice Climbing';
UPDATE activities SET energy_level = 'low' WHERE name = 'BlaBla Language Exchange (Constanța)';
UPDATE activities SET energy_level = 'low' WHERE name = 'BlaBla Language Exchange (Iași)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Black Sea Coastal Kayaking Coaching';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Black Sea Intro Dive with Marine Explorers';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Black Sea Sea-Kayaking (Mangalia)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'BOA (Beat of Angels) Hip-Hop & R&B Night';
UPDATE activities SET energy_level = 'medium' WHERE name = 'BOA Beat of Angels Luxury Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Board Game Night in Bucharest Old Town';
UPDATE activities SET energy_level = 'low' WHERE name = 'Board Game Social at The Guild Hall';
UPDATE activities SET energy_level = 'low' WHERE name = 'Board Games Night at Harmony Cafe';
UPDATE activities SET energy_level = 'low' WHERE name = 'Board Games Zone Social (Timișoara)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Board-Game Evening at Snakes & Wizards';
UPDATE activities SET energy_level = 'low' WHERE name = 'Boat Ride on Herăstrău Lake';
UPDATE activities SET energy_level = 'low' WHERE name = 'Botanical Garden: Palmhouse & remedy garden loop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Botanical Watercolor with Irina Neacșu';
UPDATE activities SET energy_level = 'high' WHERE name = 'Boxing Fitness (No Sparring)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Boxing Gym Session (Pads & Bag)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Bran Castle (Dracula''s Castle) Visit';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Brașov Old Town Walking Tour';
UPDATE activities SET energy_level = 'low' WHERE name = 'Breathwork fundamentals (Wim Hof/box/paced)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Bruno Wine Bar: Cellar Vibes';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Bucegi Plateau Hike: Babele & Sphinx';
UPDATE activities SET energy_level = 'high' WHERE name = 'Bucegi Ski Touring (Busteni/Sinaia)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Bucharest Escape Room Challenge';
UPDATE activities SET energy_level = 'low' WHERE name = 'Bucharest Language Exchange Social';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Bucharest Traditional Food Tour';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Bucharest Yoga Class (Vinyasa/Hatha)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Bucovina Painted Monasteries Tour';
UPDATE activities SET energy_level = 'high' WHERE name = 'Bungee Jump (Râșnoavei Gorge)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Buzău River Whitewater Rafting (Class III–IV) with Green Adventure';
UPDATE activities SET energy_level = 'high' WHERE name = 'Calisthenics Park Training (Parc Tei)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Calligraphy & lettering workshop';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Campus Swim at Carol Davila Pool (Cotroceni)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Ceramics Hand-Building (Alimeria Ceramics)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Chef Course at ICEP București';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Chef Course at ICEP București';
UPDATE activities SET energy_level = 'high' WHERE name = 'Cheile Râșnoavei Bungee Jump';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Cheile Turzii Gorge Guided Hike';
UPDATE activities SET energy_level = 'low' WHERE name = 'Chocolate Tasting Foundations (Artisan HUB events)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Christmas Market Bucharest (Constitution Square)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Christmas Market Cluj-Napoca (Piața Unirii)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Christmas Market Sibiu (Piața Mare)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Christmas Market Timișoara (Victory Square)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'City-Centre Swim at Novotel Wellness';
UPDATE activities SET energy_level = 'low' WHERE name = 'City-High Cocktails at NOR Sky (SkyTower)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Classic Film at Cinemateca Eforie';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Club Badminton at CSM Timișoara';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Club Badminton at CSM Timișoara';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Club Șurubelnița: Underground Party Bar';
UPDATE activities SET energy_level = 'low' WHERE name = 'Club Swim & Sun at Stejarii Country Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Cluj Escape Room Adventure';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Cluj Live Music & Club Night';
UPDATE activities SET energy_level = 'high' WHERE name = 'Cluj Tandem Paragliding at Feleacu';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Cluj-Napoca Street Food & Market Tasting';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Coastal Tennis at Tenis Club IDU';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Coastal Tennis at Tenis Club IDU';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Coastal Training at World Class Constanța';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Coastal Training at World Class Constanța';
UPDATE activities SET energy_level = 'high' WHERE name = 'Comana Adventure Park & Kayak';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Community Badminton at Banu Sport';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Community Badminton at Banu Sport';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Community Swimming at Bazinul Vega';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Community Swimming at Bazinul Vega';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Community Tennis at BDK Tennis Herăstrău';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Community Tennis at BDK Tennis Herăstrău';
UPDATE activities SET energy_level = 'high' WHERE name = 'Competitive Badminton at Badminton Club Cluj';
UPDATE activities SET energy_level = 'high' WHERE name = 'Competitive Badminton at Badminton Club Cluj';
UPDATE activities SET energy_level = 'low' WHERE name = 'Concert Night at Doors Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Constanța Seafood Tasting Experience';
UPDATE activities SET energy_level = 'low' WHERE name = 'Contemporary Jewelry Making (Assamblage Institute)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Control Club Electronic Night';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Cooking for Beginners at DallesGO';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Cooking for Beginners at DallesGO';
UPDATE activities SET energy_level = 'low' WHERE name = 'Corks Cozy Winebar Social Tasting';
UPDATE activities SET energy_level = 'low' WHERE name = 'Couples'' Photoshoot in Old Town';
UPDATE activities SET energy_level = 'low' WHERE name = 'Cowork Timișoara Language Hangout';
UPDATE activities SET energy_level = 'low' WHERE name = 'Craft Beers at Beer O''Clock';
UPDATE activities SET energy_level = 'low' WHERE name = 'Cramele Recaș Estate Visit & Tasting';
UPDATE activities SET energy_level = 'high' WHERE name = 'CrossFit Session in Bucharest';
UPDATE activities SET energy_level = 'high' WHERE name = 'CrossFit Session in Cluj';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Culinary Masterclass at Horeca School';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Culinary Masterclass at Horeca School';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Culinary Workshops at KUXA Studio';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Culinary Workshops at KUXA Studio';
UPDATE activities SET energy_level = 'low' WHERE name = 'Cyanotype & Alternative Photography Workshop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Cyanotype & Screen Printing Lab (Allkimik)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'D''Arc Unirii Sessions';
UPDATE activities SET energy_level = 'low' WHERE name = 'Danube Delta Boat Safari from Tulcea';
UPDATE activities SET energy_level = 'low' WHERE name = 'Dealu Mare Winery Trio (Lacerta/Serve/Budureasca)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Deane''s Wednesday Pub Quiz (Brașov)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Dimitrie Gusti National Village Museum';
UPDATE activities SET energy_level = 'high' WHERE name = 'Dodgeball League Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Domeniul Bogdan Organic Winery Tour';
UPDATE activities SET energy_level = 'high' WHERE name = 'Downhill & Enduro Runs (Postăvaru Bike Park)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Downhill MTB – Bike Resort Sinaia';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Drift Taxi & Hot Laps at Academia Titi Aur';
UPDATE activities SET energy_level = 'high' WHERE name = 'Edenland Park Zipline & Aerial Courses';
UPDATE activities SET energy_level = 'medium' WHERE name = 'EGO Mamaia Beach Club Nights';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Electronic Club Night in Bucharest';
UPDATE activities SET energy_level = 'low' WHERE name = 'Embroidery & Traditional Motifs – FCV';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Encanto Latin Social (Constanța)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Energiea Gastropub Social Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Ensana Sovata Spa & Saltwater Pools';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Escape Room Marathon (Central Bucharest)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Euphoria Music Hall – Big-Room Live & Party';
UPDATE activities SET energy_level = 'low' WHERE name = 'Evening acrylic painting class (Rodia Art Studio)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Evening Lanes at Dinamo Olympic Pool';
UPDATE activities SET energy_level = 'medium' WHERE name = 'ExitGames Team Escape (Timișoara)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Expirat Halele Carol Live & DJ';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Expirat Vama Veche Beach Sessions';
UPDATE activities SET energy_level = 'low' WHERE name = 'Express Beauty Reset (GETT''S Color Bar – malls)';
UPDATE activities SET energy_level = 'high' WHERE name = 'F45 HIIT Team Training';
UPDATE activities SET energy_level = 'high' WHERE name = 'Făgăraș Ski Touring Week (High Alpine)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Făgăraș Winter Mountaineering Weekend';
UPDATE activities SET energy_level = 'low' WHERE name = 'Fashion Illustration After-Work (DallesGO)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fencing Intro: Foil Basics';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fire Club: Rock & Alternative';
UPDATE activities SET energy_level = 'high' WHERE name = 'First-Time Caving – Apuseni Mountains (Guided)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Float Therapy Session (Sensory Deprivation)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Flying Circus Alt Nights';
UPDATE activities SET energy_level = 'high' WHERE name = 'Footvolley/Beach Football On Sand';
UPDATE activities SET energy_level = 'low' WHERE name = 'Foraged Cocktails at FIX Me a Drink';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fratelli Beach & Club – House by the Sea';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fratelli Iași – Luxe Mixed Music Night';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fratelli Studios High-End Clubbing';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Free-Roam VR Arena & Escape Games (Gateway VR)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'French Techniques at Disciples Escoffier';
UPDATE activities SET energy_level = 'medium' WHERE name = 'French Techniques at Disciples Escoffier';
UPDATE activities SET energy_level = 'low' WHERE name = 'Full-Day Thermal & Sauna at Therme București';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fun Bowling & Billiards at Trickshot';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fusion Cuisine at Miorita Culinary School';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fusion Cuisine at Miorita Culinary School';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Gatsby Bucharest Roaring Twenties Night';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Glam Night at Kristal Glam Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Go-Karting: VMAX (Indoor) or AMCKart (Outdoor)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Gramma Winery Visit & Tasting (Iași)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Group Cycling (Spin Class)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Group Fitness Class (HIIT/Bootcamp)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Guided Hike & Picnic in Comana Natural Park';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Guided Snowshoe Trek – Bucegi or Piatra Craiului';
UPDATE activities SET energy_level = 'low' WHERE name = 'Halotherapy & Mindful Walk – Turda Salt Mine';
UPDATE activities SET energy_level = 'low' WHERE name = 'Handmade Soap & Cosmetics Workshop';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Herăstrău Paddleboat Rental';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Herăstrău Park Bike Rental';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Herăstrău Park Rollerblading';
UPDATE activities SET energy_level = 'high' WHERE name = 'High-Altitude Ski Touring – Făgăraș (Multi-Day)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Hike & Picnic at Comana Natural Park';
UPDATE activities SET energy_level = 'high' WHERE name = 'Hiking & Scrambling: Piatra Craiului Ridge';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Hip-Hop & R&B at BOA (Beat of Angels)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Horseback Riding Lesson (Beginner)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Hot Air Balloon Flight near Cluj';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Iași Night Out (Bars & Clubs)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Ice Climbing Intro – Bâlea Waterfall';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Ice Skating Session (AFI Cotroceni)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Icon on Glass Workshop (ASTRA Museum)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Immersive Escape Room Adventure';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Improvisation Theatre Workshop (Bucharest)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Indoor Bouldering Session';
UPDATE activities SET energy_level = 'high' WHERE name = 'Indoor Climbing Session (Top-rope & Bouldering)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Indoor Rock Climbing (Vertical Gym)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Intro to Golf in Transylvania';
UPDATE activities SET energy_level = 'low' WHERE name = 'Intro to Romanian Wine (Bucharest)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Jazz Night at Green Hours';
UPDATE activities SET energy_level = 'low' WHERE name = 'Karaoke Night at Mojo Music Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Kayaking on Snagov Lake';
UPDATE activities SET energy_level = 'high' WHERE name = 'Kitesurfing Intro (Mamaia)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Kristal Glam Club: Luxe Night Out';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Kulturhaus Bucharest Student Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Language Exchange at Seneca AntiCafe';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Laser Tag Battles';
UPDATE activities SET energy_level = 'low' WHERE name = 'Late-Night Cocktails at Joben Bistro';
UPDATE activities SET energy_level = 'low' WHERE name = 'Late-Night Lounge at Uanderful';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Leaota Mountain Horseback Trail Ride';
UPDATE activities SET energy_level = 'low' WHERE name = 'Leather Crafting Basics (Handmade Wallets/Belts)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Linea / Closer to the Moon Rooftop Cocktails';
UPDATE activities SET energy_level = 'low' WHERE name = 'Live Jazz at Green Hours 22';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Live Music at Expirat Halele Carol';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Live Music at Fire Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Live Music at The Fool';
UPDATE activities SET energy_level = 'low' WHERE name = 'Live Music Night at Berăria H';
UPDATE activities SET energy_level = 'low' WHERE name = 'Macrame Plant Hanger Workshop';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Mamaia Beach Volleyball';
UPDATE activities SET energy_level = 'high' WHERE name = 'Mamaia Kitesurfing Intro';
UPDATE activities SET energy_level = 'high' WHERE name = 'Mamaia Windsurfing Intro';
UPDATE activities SET energy_level = 'low' WHERE name = 'Metalworking & Welding Intro (NOD Makerspace)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Mindful Swim at Stejarii Country Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Mixology Masterclass (Cocktail Basics)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Modern Dance Class (Contemporary/Jazz)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Mojo Music Club Karaoke Night';
UPDATE activities SET energy_level = 'high' WHERE name = 'Motorcycle Track Day (MotorPark Romania)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Mountain Biking (Sinaia Trails)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Mountain Biking – Postăvaru Bike Park';
UPDATE activities SET energy_level = 'high' WHERE name = 'Muay Thai Kickboxing Class';
UPDATE activities SET energy_level = 'high' WHERE name = 'Multi-Pitch Climbing – Vânturătoarea Ridge (Bucegi)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Museum Hopping: MNAC + Village Museum';
UPDATE activities SET energy_level = 'low' WHERE name = 'Natural Cosmetics DIY (Soap/Balm/Scrub)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Natural Wine Tasting at Corks';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Nightlife Crawl: Lipscani Old Town Bars';
UPDATE activities SET energy_level = 'low' WHERE name = 'NOMAD Skybar Rooftop Cocktails';
UPDATE activities SET energy_level = 'low' WHERE name = 'NOR Sky Rooftop Dinner for Two';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Off-Road Driving Experience (4x4 Trails)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Oil Painting Basics (Rodia Art Studio)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Old Town Pub Crawl';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Olympic Pool Session at Dinamo';
UPDATE activities SET energy_level = 'high' WHERE name = 'One-Day Ski Touring Intro – Bucegi';
UPDATE activities SET energy_level = 'low' WHERE name = 'Oradea Thermal Aqua Day (Aquaparks)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Outdoor Yoga in Herăstrău Park';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Padel Court Booking (Romexpo Area)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Paintball Battle (Outdoor Arena)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Parc Aventura Brașov Zipline & Ropes';
UPDATE activities SET energy_level = 'low' WHERE name = 'Peleș Castle Guided Visit';
UPDATE activities SET energy_level = 'low' WHERE name = 'Perfume-Making Workshop (Scent Design)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Pilates Mat Class';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Ping-Pong Social at Ping Pong Academy';
UPDATE activities SET energy_level = 'high' WHERE name = 'Poiana Brașov Downhill Mountain Biking';
UPDATE activities SET energy_level = 'high' WHERE name = 'Poiana Brașov Skiing & Snowboarding';
UPDATE activities SET energy_level = 'low' WHERE name = 'Pottery Wheel Throwing Class';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Premium Swim at World Class (Mega Mall)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Private Boat Ride on Herăstrău Lake';
UPDATE activities SET energy_level = 'low' WHERE name = 'Private Snagov Lake Boat Cruise';
UPDATE activities SET energy_level = 'low' WHERE name = 'Pub Quiz Night in the Old Town (Mojo & The PUB)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Public Speaking Practice (Toastmasters Bucharest)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick Reset: Bookstore Browsing at Cărturești';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick Reset: Botanical Garden Rosarium Loop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick Reset: Carol Park Mausoleum Viewpoint Bench';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick Reset: Cișmigiu Gardens Quiet Loop & Bench 7';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick Reset: Kiseleff Shaded Boulevard Benches';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick Reset: Macca–Vilacrosse Passage Stroll';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick Reset: MNAC Rooftop Terrace View';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick reset: Saint Roastery coffee stop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick reset: Throwback Dorobanți';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick Reset: Titan (A.I. Cuza) Lakeside – Insula Artelor';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quick reset: Two Minutes Coffee Shop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quiet bench: Grădina Icoanei';
UPDATE activities SET energy_level = 'low' WHERE name = 'Quiet bench: Parcul Circului (Lotus Lake)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Resin Art: Pour & Finish (NOD cursuri)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Retezat Backcountry Ski (6-Day)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Retezat National Park Day Hike';
UPDATE activities SET energy_level = 'low' WHERE name = 'Retro Café Board-Game Social';
UPDATE activities SET energy_level = 'low' WHERE name = 'Rhein Azuga 1892 Cellar Tour & Bubbles';
UPDATE activities SET energy_level = 'high' WHERE name = 'Rock Ridge Climb – Acele Morarului (Bucegi)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Romanian Cooking Class in Bucharest';
UPDATE activities SET energy_level = 'low' WHERE name = 'Romanian Language Crash Course (Bucharest)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Romantic Boat Ride on Herăstrău Lake';
UPDATE activities SET energy_level = 'low' WHERE name = 'Romantic Candlelight Concert (Fever)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Rooftop Cocktails at Linea/Closer to the Moon';
UPDATE activities SET energy_level = 'low' WHERE name = 'Rooftop Cocktails at NOMAD Skybar';
UPDATE activities SET energy_level = 'low' WHERE name = 'Rooftop Sundowners at Linea / Closer to the Moon';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Rugby Intro Session (Non-contact Basics)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Runners Club Cluj – Social Run';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Salsa/Bachata Beginner Class (Bucharest)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Salt Mine Wellness Session – Praid';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Scărișoara Ice Cave & Apuseni Views';
UPDATE activities SET energy_level = 'low' WHERE name = 'Scârț Loc Lejer Living-Room Lounge';
UPDATE activities SET energy_level = 'low' WHERE name = 'Screen Printing Basics (Bucharest)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Scuba Diving — Discover Scuba (DSD)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Self-Guided Architecture Audio Walk (Old Town)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Semi-Olympic Session at World Class Mega Mall (Pantelimon)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Seneca AntiCafe – Board Game & Social Work Sesh';
UPDATE activities SET energy_level = 'high' WHERE name = 'Seven Ladders Canyon Tyrolean Zipline (Dâmbul Morii)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Seven Ladders Canyon Via Ferrata Sprint';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sewing & Patternmaking Basics (Atelierele ILBAH)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sewing Basics – Atelierele ILBAH';
UPDATE activities SET energy_level = 'low' WHERE name = 'Shiseido Spa Rituals at Stejarii Country Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'SHOTERIA Old Town: Rapid-Fire Shots';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Sibiu Old Town Food Tour';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Sibiu Traditional Cooking Class';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sip & Paint Night (PaintandParty.ro)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Skiing in Poiana Brașov';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Social Badminton at WePlay Brașov';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Social Badminton at WePlay Brașov';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Social Ping-Pong at Ping Pong Academy';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sound Bath & Breathwork (Bucharest)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sound bath with gongs & bowls';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Sourdough & Pastry Fundamentals (Horeca Culinary School)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sovata Bear Lake & Spa Day';
UPDATE activities SET energy_level = 'low' WHERE name = 'Specialty Coffee Brewing Class (Bucharest)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Specialty Coffee Cupping & Barista Basics';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sports & Pints at St. Patrick Irish Pub';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sports Bar Titan: Billiards & Darts';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Sports Hall Badminton at Sala STOMART';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Sports Hall Badminton at Sala STOMART';
UPDATE activities SET energy_level = 'high' WHERE name = 'Squash Session & Coaching (Central-East)';
UPDATE activities SET energy_level = 'low' WHERE name = 'St. Patrick Irish Pub: Sports & Pints';
UPDATE activities SET energy_level = 'low' WHERE name = 'Stained Glass (Tiffany Technique) Workshop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Stained Glass (Tiffany Technique) Workshop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Stained Glass (Tiffany) Intro Workshop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Stand-Up Night at The Fool Comedy Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Stand-Up Paddle (City Session)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Stargazing at Vasile Urseanu Observatory';
UPDATE activities SET energy_level = 'low' WHERE name = 'Steampunk Cocktails at Joben';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Student Club Badminton at Sportul Studențesc';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Student Club Badminton at Sportul Studențesc';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Student Night at Kulturhaus Bucharest';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sunset Rooftops at 18 Lounge (City Gate)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sunset Splash at Magic Place Aqua Park';
UPDATE activities SET energy_level = 'high' WHERE name = 'Surfing Lesson (Black Sea)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Table Tennis Club Session';
UPDATE activities SET energy_level = 'low' WHERE name = 'Tai Chi & Qigong Classes (Taijidao)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Paragliding Clopotiva (Retezat)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Skydive – Tuzla Aerodrome (Black Sea)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Skydive at Clinceni (TNT Brothers)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Skydive at Clinceni (TNT Brothers)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Skydive Luncani (Skydive Transilvania)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Skydive over the Black Sea (Tuzla)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Skydive Timișoara (GoJump LRSG)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Skydiving at Clinceni Airfield';
UPDATE activities SET energy_level = 'high' WHERE name = 'Tandem Skydiving over Cluj with Skydive Transilvania';
UPDATE activities SET energy_level = 'low' WHERE name = 'Tea Tasting & Ceremony (Cotroceni Teahouses)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Team Escape at Captive';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Tech-House Marathon at Kristal Glam Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Technical University Pool at UTCN';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Technical University Pool at UTCN';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Tennis Lesson Or Court (Herăstrău)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Thai Massage & Aromatherapy (THAIco Spa Dorobanți)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'The Dungeon – Team Escape Night';
UPDATE activities SET energy_level = 'medium' WHERE name = 'The Escapers Team Escape (Constanța)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Therme București Full-Day Thermal Spa';
UPDATE activities SET energy_level = 'low' WHERE name = 'Therme București Wellness Day';
UPDATE activities SET energy_level = 'low' WHERE name = 'Therme Sauna Rituals & Mindful Heat';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Timisoara Club Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Timișoara Craft Beer Tasting Crawl';
UPDATE activities SET energy_level = 'low' WHERE name = 'Tipografia Culture Bar';
UPDATE activities SET energy_level = 'low' WHERE name = 'Toastmasters Public Speaking Night (Constanța)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Toastmasters Public Speaking Night (Iași)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Toastmasters Public Speaking Night (Timișoara)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Track Day Laps at MotorPark Romania';
UPDATE activities SET energy_level = 'high' WHERE name = 'Track Session (Iolanda Balaș-Soter)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Traditional Cookery at Casa Ratiu';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Traditional Cookery at Casa Ratiu';
UPDATE activities SET energy_level = 'low' WHERE name = 'Traditional Embroidery at Casa cu Rost';
UPDATE activities SET energy_level = 'low' WHERE name = 'Traditional Pottery at Ceramica de Nocrich';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Traditional Rowing (Canotcă) Basics';
UPDATE activities SET energy_level = 'high' WHERE name = 'Trail Running Clinic (Brașov)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Training & Play at ACS Pro Badminton';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Training & Play at ACS Pro Badminton';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Training Session at Bazinul Olimpic Dinamo';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Training Session at Bazinul Olimpic Dinamo';
UPDATE activities SET energy_level = 'low' WHERE name = 'Transfăgărășan Scenic Day Tour';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Transylvanian Laps at Bazinul Olimpic Târgu Mureș';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Transylvanian Laps at Bazinul Olimpic Târgu Mureș';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Trickshot AFI Cotroceni: Lanes & Cocktails';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Trickshot Mega Mall: Bowling & Bar';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Trickshot Promenada Rooftop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Turda Salt Mine Underground Park';
UPDATE activities SET energy_level = 'low' WHERE name = 'Uanderful: Floreasca Lounge & Late Drinks';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Ultimate Frisbee Pickup Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Underground The Pub: Iași Rock Cellar';
UPDATE activities SET energy_level = 'medium' WHERE name = 'University Pool at Complexul de Natație UBB';
UPDATE activities SET energy_level = 'medium' WHERE name = 'University Pool at Complexul de Natație UBB';
UPDATE activities SET energy_level = 'low' WHERE name = 'Urban Hammam & Thermal Circuit (Orhideea Spa)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Urban Nature Walk & Birdwatching (Văcărești)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Urban Tennis at Tenis Club AS';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Urban Tennis at Tenis Club AS';
UPDATE activities SET energy_level = 'high' WHERE name = 'Vertical Spirit Social Climb Night';
UPDATE activities SET energy_level = 'high' WHERE name = 'Via Ferrata "Casa Zmeului"';
UPDATE activities SET energy_level = 'high' WHERE name = 'Via Ferrata Casa Zmeului – Vadu Crișului';
UPDATE activities SET energy_level = 'high' WHERE name = 'Via Ferrata Casa Zmeului (Vadu Crișului)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Via Ferrata Hili''s Cave (Cheile Turzii)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Via Ferrata Pietrele Negre – Vârtop (Apuseni)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Via Ferrata Wild Ferenc in Bicaz Gorges';
UPDATE activities SET energy_level = 'low' WHERE name = 'Village Museum Curated Guided Tour';
UPDATE activities SET energy_level = 'low' WHERE name = 'Vineri 15 Riverfront Quiz Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Viniloteca: Wine & Wax Nights';
UPDATE activities SET energy_level = 'medium' WHERE name = 'VIP Glam Night at BOA - Beat of Angels';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Viscri Pastures Bike & Haystack Walk';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Volleyball Social Play – CCSS Tei';
UPDATE activities SET energy_level = 'high' WHERE name = 'Wakeboarding Session near Bucharest';
UPDATE activities SET energy_level = 'low' WHERE name = 'Weaving on the Loom (ASTRA Museum)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Wellness & Tennis at Pescariu Sports';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Wellness & Tennis at Pescariu Sports';
UPDATE activities SET energy_level = 'low' WHERE name = 'Wellness visit: Salina Turda (salt mine)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Western Tennis at Tenis Timișoara';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Western Tennis at Tenis Timișoara';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Western Training at Bazinul Olimpic Ioan Alexandrescu';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Western Training at Bazinul Olimpic Ioan Alexandrescu';
UPDATE activities SET energy_level = 'low' WHERE name = 'Wheel Throwing Intro at Clay Play';
UPDATE activities SET energy_level = 'low' WHERE name = 'Wheel Throwing Starter at Em Chang Studio';
UPDATE activities SET energy_level = 'low' WHERE name = 'Wheel-throwing taster at CUBUL';
UPDATE activities SET energy_level = 'high' WHERE name = 'Windsurfing Intro (Mamaia)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Wine Tasting in Dealu Mare';
UPDATE activities SET energy_level = 'low' WHERE name = 'Woodworking Basics at NOD Makerspace';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Year-Round Swimming at Aria Aqua Park';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Year-Round Swimming at Aria Aqua Park';
UPDATE activities SET energy_level = 'low' WHERE name = 'Yolka Skybar Sundowners';
UPDATE activities SET energy_level = 'low' WHERE name = 'ZborHub Language Exchange (Brașov)';
UPDATE activities SET energy_level = 'high' WHERE name = 'Zipline & Rope Courses at Comana Adventure Park';
UPDATE activities SET energy_level = 'high' WHERE name = 'Zumba Dance Fitness';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Affordable Lengths at Olimpia (Iancului)';
UPDATE activities SET energy_level = 'low' WHERE name = 'After-Work Dip at Daimon Wellness (Tineretului)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Alt & Electronic Nights at Control Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Alt-Rock & Indie Nights at Expirat';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Beach Club Night at EGO Mamaia';
UPDATE activities SET energy_level = 'low' WHERE name = 'Beer O''Clock: Craft & Imports';
UPDATE activities SET energy_level = 'low' WHERE name = 'Beluga: Music & Cocktails (Old Town)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Berăria H Beer Hall & Live Shows';
UPDATE activities SET energy_level = 'medium' WHERE name = 'BOA (Beat of Angels) Hip-Hop & R&B Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Board-Game Evening at Snakes & Wizards';
UPDATE activities SET energy_level = 'low' WHERE name = 'Bruno Wine Bar: Cellar Vibes';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Campus Swim at Carol Davila Pool (Cotroceni)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'City-Centre Swim at Novotel Wellness';
UPDATE activities SET energy_level = 'low' WHERE name = 'City-High Cocktails at NOR Sky (SkyTower)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Club Șurubelnița: Underground Party Bar';
UPDATE activities SET energy_level = 'low' WHERE name = 'Club Swim & Sun at Stejarii Country Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Concert Night at Doors Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Craft Beers at Beer O''Clock';
UPDATE activities SET energy_level = 'medium' WHERE name = 'D''Arc Unirii Sessions';
UPDATE activities SET energy_level = 'medium' WHERE name = 'EGO Mamaia Beach Club Nights';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Euphoria Music Hall – Big-Room Live & Party';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Evening Lanes at Dinamo Olympic Pool';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Expirat Vama Veche Beach Sessions';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fire Club: Rock & Alternative';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Flying Circus Alt Nights';
UPDATE activities SET energy_level = 'low' WHERE name = 'Foraged Cocktails at FIX Me a Drink';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fratelli Beach & Club – House by the Sea';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Fratelli Iași – Luxe Mixed Music Night';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Grand Lanes at World Class The Grand (JW Marriott)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Halftime Sports Pub (Gabroveni)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'High-End Night at Epic Society';
UPDATE activities SET energy_level = 'medium' WHERE name = 'High-Gloss Nights at E3 by Entourage';
UPDATE activities SET energy_level = 'low' WHERE name = 'Hookah & Lounge at Macca-Villacrosse (Hugo)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'House Night at Fratelli Lounge & Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Infinity Hookah Lounge (Eminescu)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Intimate Jazz Night at Green Hours';
UPDATE activities SET energy_level = 'low' WHERE name = 'Jazz & Blues Club Târgu Mureș';
UPDATE activities SET energy_level = 'low' WHERE name = 'KIKI Lounge & Bar (LGBTQ+ friendly) Cocktails';
UPDATE activities SET energy_level = 'low' WHERE name = 'KLANdestin: IOR Park View Drinks';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Laps & Steam at Crowne Plaza ANA Spa';
UPDATE activities SET energy_level = 'low' WHERE name = 'LINEA / Closer to the Moon Rooftop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Live Anthems at Hard Rock Cafe Bucharest';
UPDATE activities SET energy_level = 'low' WHERE name = 'Live Band & Karaoke at Mojo Music Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Live Jazz at Jazz & Blues Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Live Jazz Sessions at The JAZZ BOOK';
UPDATE activities SET energy_level = 'low' WHERE name = 'Lokal Oradea Rooftop Sundowners';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Metal Nights at Rockstadt';
UPDATE activities SET energy_level = 'low' WHERE name = 'Mojo: Karaoke & Live Band Nights';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Moszkva Oradea Alt Scene';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Music Pub Sibiu Rock Nights';
UPDATE activities SET energy_level = 'low' WHERE name = 'Nova Lounge & Hookah (Ferdinand)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Origo Cocktail Evenings (Old Town)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Peak Weekend at FACE Club';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Premium Party at NOA – Nest of Angels';
UPDATE activities SET energy_level = 'low' WHERE name = 'Pura Vida Sky Bar (Old Town)';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Quantic: Rock & Metal Live';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Queens Club LGBTQ+ Night';
UPDATE activities SET energy_level = 'low' WHERE name = 'Rooftop Cocktails at NOMAD Skybar';
UPDATE activities SET energy_level = 'low' WHERE name = 'Rooftop Sundowners at Linea / Closer to the Moon';
UPDATE activities SET energy_level = 'low' WHERE name = 'Scârț Loc Lejer Living-Room Lounge';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Semi-Olympic Session at World Class Mega Mall (Pantelimon)';
UPDATE activities SET energy_level = 'low' WHERE name = 'SHOTERIA Old Town: Rapid-Fire Shots';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sports & Pints at St. Patrick Irish Pub';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sports Bar Titan: Billiards & Darts';
UPDATE activities SET energy_level = 'low' WHERE name = 'St. Patrick Irish Pub: Sports & Pints';
UPDATE activities SET energy_level = 'low' WHERE name = 'Stand-Up Night at The Fool Comedy Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Steampunk Cocktails at Joben';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Student Night at Kulturhaus Bucharest';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sunset Rooftops at 18 Lounge (City Gate)';
UPDATE activities SET energy_level = 'low' WHERE name = 'Sunset Splash at Magic Place Aqua Park';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Tech-House Marathon at Kristal Glam Club';
UPDATE activities SET energy_level = 'low' WHERE name = 'Tipografia Culture Bar';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Trickshot AFI Cotroceni: Lanes & Cocktails';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Trickshot Mega Mall: Bowling & Bar';
UPDATE activities SET energy_level = 'medium' WHERE name = 'Trickshot Promenada Rooftop';
UPDATE activities SET energy_level = 'low' WHERE name = 'Uanderful: Floreasca Lounge & Late Drinks';
UPDATE activities SET energy_level = 'low' WHERE name = 'Underground The Pub: Iași Rock Cellar';
UPDATE activities SET energy_level = 'low' WHERE name = 'Viniloteca: Wine & Wax Nights';
UPDATE activities SET energy_level = 'medium' WHERE name = 'VIP Glam Night at BOA - Beat of Angels';
UPDATE activities SET energy_level = 'low' WHERE name = 'Yolka Skybar Sundowners';
